// Copyright 2025 Moonshine AI
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../core
#cgo LDFLAGS: -L${SRCDIR}/../../../core/build -lmoonshine
#include "moonshine-c-api.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// allocStructMoonshineOptionTMemory allocates memory for type C.struct_moonshine_option_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStructMoonshineOptionTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStructMoonshineOptionTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStructMoonshineOptionTValue = unsafe.Sizeof([1]C.struct_moonshine_option_t{})

// copyPCharBytes copies the data from Go slice as *C.char.
func copyPCharBytes(slice *sliceHeader) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfCharValue) * slice.Len,
		Cap:  int(sizeOfCharValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.char)(mem0), allocs
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// allocCharMemory allocates memory for type C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfCharValue = unsafe.Sizeof([1]C.char{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *MoonshineOptionT) Ref() *C.struct_moonshine_option_t {
	if x == nil {
		return nil
	}
	return x.ref49bfe3c9
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *MoonshineOptionT) Free() {
	if x != nil && x.allocs49bfe3c9 != nil {
		x.allocs49bfe3c9.(*cgoAllocMap).Free()
		x.ref49bfe3c9 = nil
	}
}

// NewMoonshineOptionTRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewMoonshineOptionTRef(ref unsafe.Pointer) *MoonshineOptionT {
	if ref == nil {
		return nil
	}
	obj := new(MoonshineOptionT)
	obj.ref49bfe3c9 = (*C.struct_moonshine_option_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *MoonshineOptionT) PassRef() (*C.struct_moonshine_option_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref49bfe3c9 != nil {
		return x.ref49bfe3c9, nil
	}
	mem49bfe3c9 := allocStructMoonshineOptionTMemory(1)
	ref49bfe3c9 := (*C.struct_moonshine_option_t)(mem49bfe3c9)
	allocs49bfe3c9 := new(cgoAllocMap)
	allocs49bfe3c9.Add(mem49bfe3c9)

	var cname_allocs *cgoAllocMap
	ref49bfe3c9.name, cname_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Name)))
	allocs49bfe3c9.Borrow(cname_allocs)

	var cvalue_allocs *cgoAllocMap
	ref49bfe3c9.value, cvalue_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Value)))
	allocs49bfe3c9.Borrow(cvalue_allocs)

	x.ref49bfe3c9 = ref49bfe3c9
	x.allocs49bfe3c9 = allocs49bfe3c9
	return ref49bfe3c9, allocs49bfe3c9

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x MoonshineOptionT) PassValue() (C.struct_moonshine_option_t, *cgoAllocMap) {
	if x.ref49bfe3c9 != nil {
		return *x.ref49bfe3c9, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *MoonshineOptionT) Deref() {
	if x.ref49bfe3c9 == nil {
		return
	}
	hxfc4425b := (*sliceHeader)(unsafe.Pointer(&x.Name))
	hxfc4425b.Data = unsafe.Pointer(x.ref49bfe3c9.name)
	hxfc4425b.Cap = 0x7fffffff
	// hxfc4425b.Len = ? x.Name x.ref49bfe3c9.name

	hxf95e7c8 := (*sliceHeader)(unsafe.Pointer(&x.Value))
	hxf95e7c8.Data = unsafe.Pointer(x.ref49bfe3c9.value)
	hxf95e7c8.Cap = 0x7fffffff
	// hxf95e7c8.Len = ? x.Value x.ref49bfe3c9.value

}

// allocStructMoonshineSpeechClipTMemory allocates memory for type C.struct_moonshine_speech_clip_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStructMoonshineSpeechClipTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStructMoonshineSpeechClipTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStructMoonshineSpeechClipTValue = unsafe.Sizeof([1]C.struct_moonshine_speech_clip_t{})

// copyPFloatBytes copies the data from Go slice as *C.float.
func copyPFloatBytes(slice *sliceHeader) (*C.float, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfFloatValue) * slice.Len,
		Cap:  int(sizeOfFloatValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.float)(mem0), allocs
}

// allocFloatMemory allocates memory for type C.float in C.
// The caller is responsible for freeing the this memory via C.free.
func allocFloatMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfFloatValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfFloatValue = unsafe.Sizeof([1]C.float{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *MoonshineSpeechClipT) Ref() *C.struct_moonshine_speech_clip_t {
	if x == nil {
		return nil
	}
	return x.ref48734c3f
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *MoonshineSpeechClipT) Free() {
	if x != nil && x.allocs48734c3f != nil {
		x.allocs48734c3f.(*cgoAllocMap).Free()
		x.ref48734c3f = nil
	}
}

// NewMoonshineSpeechClipTRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewMoonshineSpeechClipTRef(ref unsafe.Pointer) *MoonshineSpeechClipT {
	if ref == nil {
		return nil
	}
	obj := new(MoonshineSpeechClipT)
	obj.ref48734c3f = (*C.struct_moonshine_speech_clip_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *MoonshineSpeechClipT) PassRef() (*C.struct_moonshine_speech_clip_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref48734c3f != nil {
		return x.ref48734c3f, nil
	}
	mem48734c3f := allocStructMoonshineSpeechClipTMemory(1)
	ref48734c3f := (*C.struct_moonshine_speech_clip_t)(mem48734c3f)
	allocs48734c3f := new(cgoAllocMap)
	allocs48734c3f.Add(mem48734c3f)

	var caudio_data_allocs *cgoAllocMap
	ref48734c3f.audio_data, caudio_data_allocs = copyPFloatBytes((*sliceHeader)(unsafe.Pointer(&x.AudioData)))
	allocs48734c3f.Borrow(caudio_data_allocs)

	var caudio_length_allocs *cgoAllocMap
	ref48734c3f.audio_length, caudio_length_allocs = (C.uint64_t)(x.AudioLength), cgoAllocsUnknown
	allocs48734c3f.Borrow(caudio_length_allocs)

	var cstart_time_allocs *cgoAllocMap
	ref48734c3f.start_time, cstart_time_allocs = (C.float)(x.StartTime), cgoAllocsUnknown
	allocs48734c3f.Borrow(cstart_time_allocs)

	var cspeech_duration_allocs *cgoAllocMap
	ref48734c3f.speech_duration, cspeech_duration_allocs = (C.float)(x.SpeechDuration), cgoAllocsUnknown
	allocs48734c3f.Borrow(cspeech_duration_allocs)

	var cis_complete_allocs *cgoAllocMap
	ref48734c3f.is_complete, cis_complete_allocs = (C.int32_t)(x.IsComplete), cgoAllocsUnknown
	allocs48734c3f.Borrow(cis_complete_allocs)

	var ctranscript_allocs *cgoAllocMap
	ref48734c3f.transcript, ctranscript_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Transcript)))
	allocs48734c3f.Borrow(ctranscript_allocs)

	x.ref48734c3f = ref48734c3f
	x.allocs48734c3f = allocs48734c3f
	return ref48734c3f, allocs48734c3f

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x MoonshineSpeechClipT) PassValue() (C.struct_moonshine_speech_clip_t, *cgoAllocMap) {
	if x.ref48734c3f != nil {
		return *x.ref48734c3f, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *MoonshineSpeechClipT) Deref() {
	if x.ref48734c3f == nil {
		return
	}
	hxff2234b := (*sliceHeader)(unsafe.Pointer(&x.AudioData))
	hxff2234b.Data = unsafe.Pointer(x.ref48734c3f.audio_data)
	hxff2234b.Cap = 0x7fffffff
	// hxff2234b.Len = ? x.AudioData x.ref48734c3f.audio_data

	x.AudioLength = (uint64)(x.ref48734c3f.audio_length)
	x.StartTime = (float32)(x.ref48734c3f.start_time)
	x.SpeechDuration = (float32)(x.ref48734c3f.speech_duration)
	x.IsComplete = (int32)(x.ref48734c3f.is_complete)
	hxff73280 := (*sliceHeader)(unsafe.Pointer(&x.Transcript))
	hxff73280.Data = unsafe.Pointer(x.ref48734c3f.transcript)
	hxff73280.Cap = 0x7fffffff
	// hxff73280.Len = ? x.Transcript x.ref48734c3f.transcript

}

// allocStructSpeakerSpanTMemory allocates memory for type C.struct_speaker_span_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStructSpeakerSpanTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStructSpeakerSpanTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStructSpeakerSpanTValue = unsafe.Sizeof([1]C.struct_speaker_span_t{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *SpeakerSpanT) Ref() *C.struct_speaker_span_t {
	if x == nil {
		return nil
	}
	return x.refc74b8359
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *SpeakerSpanT) Free() {
	if x != nil && x.allocsc74b8359 != nil {
		x.allocsc74b8359.(*cgoAllocMap).Free()
		x.refc74b8359 = nil
	}
}

// NewSpeakerSpanTRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewSpeakerSpanTRef(ref unsafe.Pointer) *SpeakerSpanT {
	if ref == nil {
		return nil
	}
	obj := new(SpeakerSpanT)
	obj.refc74b8359 = (*C.struct_speaker_span_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *SpeakerSpanT) PassRef() (*C.struct_speaker_span_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.refc74b8359 != nil {
		return x.refc74b8359, nil
	}
	memc74b8359 := allocStructSpeakerSpanTMemory(1)
	refc74b8359 := (*C.struct_speaker_span_t)(memc74b8359)
	allocsc74b8359 := new(cgoAllocMap)
	allocsc74b8359.Add(memc74b8359)

	var cstart_time_allocs *cgoAllocMap
	refc74b8359.start_time, cstart_time_allocs = (C.float)(x.StartTime), cgoAllocsUnknown
	allocsc74b8359.Borrow(cstart_time_allocs)

	var cduration_allocs *cgoAllocMap
	refc74b8359.duration, cduration_allocs = (C.float)(x.Duration), cgoAllocsUnknown
	allocsc74b8359.Borrow(cduration_allocs)

	var cspeaker_id_allocs *cgoAllocMap
	refc74b8359.speaker_id, cspeaker_id_allocs = (C.uint64_t)(x.SpeakerId), cgoAllocsUnknown
	allocsc74b8359.Borrow(cspeaker_id_allocs)

	var cspeaker_index_allocs *cgoAllocMap
	refc74b8359.speaker_index, cspeaker_index_allocs = (C.uint32_t)(x.SpeakerIndex), cgoAllocsUnknown
	allocsc74b8359.Borrow(cspeaker_index_allocs)

	var cstart_char_allocs *cgoAllocMap
	refc74b8359.start_char, cstart_char_allocs = (C.uint64_t)(x.StartChar), cgoAllocsUnknown
	allocsc74b8359.Borrow(cstart_char_allocs)

	var cend_char_allocs *cgoAllocMap
	refc74b8359.end_char, cend_char_allocs = (C.uint64_t)(x.EndChar), cgoAllocsUnknown
	allocsc74b8359.Borrow(cend_char_allocs)

	x.refc74b8359 = refc74b8359
	x.allocsc74b8359 = allocsc74b8359
	return refc74b8359, allocsc74b8359

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x SpeakerSpanT) PassValue() (C.struct_speaker_span_t, *cgoAllocMap) {
	if x.refc74b8359 != nil {
		return *x.refc74b8359, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *SpeakerSpanT) Deref() {
	if x.refc74b8359 == nil {
		return
	}
	x.StartTime = (float32)(x.refc74b8359.start_time)
	x.Duration = (float32)(x.refc74b8359.duration)
	x.SpeakerId = (uint64)(x.refc74b8359.speaker_id)
	x.SpeakerIndex = (uint32)(x.refc74b8359.speaker_index)
	x.StartChar = (uint64)(x.refc74b8359.start_char)
	x.EndChar = (uint64)(x.refc74b8359.end_char)
}

// allocStructTranscriptLineTMemory allocates memory for type C.struct_transcript_line_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStructTranscriptLineTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStructTranscriptLineTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStructTranscriptLineTValue = unsafe.Sizeof([1]C.struct_transcript_line_t{})

const sizeOfPtr = unsafe.Sizeof(&struct{}{})

// unpackSSpeakerSpanT transforms a sliced Go data structure into plain C format.
func unpackSSpeakerSpanT(x []SpeakerSpanT) (unpacked *C.struct_speaker_span_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStructSpeakerSpanTMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.struct_speaker_span_t)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.struct_speaker_span_t)(h.Data)
	return
}

// allocStructTranscriptWordTMemory allocates memory for type C.struct_transcript_word_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStructTranscriptWordTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStructTranscriptWordTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStructTranscriptWordTValue = unsafe.Sizeof([1]C.struct_transcript_word_t{})

// unpackSTranscriptWordT transforms a sliced Go data structure into plain C format.
func unpackSTranscriptWordT(x []TranscriptWordT) (unpacked *C.struct_transcript_word_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStructTranscriptWordTMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.struct_transcript_word_t)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.struct_transcript_word_t)(h.Data)
	return
}

// packSSpeakerSpanT reads sliced Go data structure out from plain C format.
func packSSpeakerSpanT(v []SpeakerSpanT, ptr0 *C.struct_speaker_span_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStructSpeakerSpanTValue]C.struct_speaker_span_t)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewSpeakerSpanTRef(unsafe.Pointer(&ptr1))
	}
}

// packSTranscriptWordT reads sliced Go data structure out from plain C format.
func packSTranscriptWordT(v []TranscriptWordT, ptr0 *C.struct_transcript_word_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStructTranscriptWordTValue]C.struct_transcript_word_t)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewTranscriptWordTRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *TranscriptLineT) Ref() *C.struct_transcript_line_t {
	if x == nil {
		return nil
	}
	return x.ref4f437f7c
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *TranscriptLineT) Free() {
	if x != nil && x.allocs4f437f7c != nil {
		x.allocs4f437f7c.(*cgoAllocMap).Free()
		x.ref4f437f7c = nil
	}
}

// NewTranscriptLineTRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewTranscriptLineTRef(ref unsafe.Pointer) *TranscriptLineT {
	if ref == nil {
		return nil
	}
	obj := new(TranscriptLineT)
	obj.ref4f437f7c = (*C.struct_transcript_line_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *TranscriptLineT) PassRef() (*C.struct_transcript_line_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref4f437f7c != nil {
		return x.ref4f437f7c, nil
	}
	mem4f437f7c := allocStructTranscriptLineTMemory(1)
	ref4f437f7c := (*C.struct_transcript_line_t)(mem4f437f7c)
	allocs4f437f7c := new(cgoAllocMap)
	allocs4f437f7c.Add(mem4f437f7c)

	var ctext_allocs *cgoAllocMap
	ref4f437f7c.text, ctext_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Text)))
	allocs4f437f7c.Borrow(ctext_allocs)

	var caudio_data_allocs *cgoAllocMap
	ref4f437f7c.audio_data, caudio_data_allocs = copyPFloatBytes((*sliceHeader)(unsafe.Pointer(&x.AudioData)))
	allocs4f437f7c.Borrow(caudio_data_allocs)

	var caudio_data_count_allocs *cgoAllocMap
	ref4f437f7c.audio_data_count, caudio_data_count_allocs = (C.size_t)(x.AudioDataCount), cgoAllocsUnknown
	allocs4f437f7c.Borrow(caudio_data_count_allocs)

	var cstart_time_allocs *cgoAllocMap
	ref4f437f7c.start_time, cstart_time_allocs = (C.float)(x.StartTime), cgoAllocsUnknown
	allocs4f437f7c.Borrow(cstart_time_allocs)

	var cduration_allocs *cgoAllocMap
	ref4f437f7c.duration, cduration_allocs = (C.float)(x.Duration), cgoAllocsUnknown
	allocs4f437f7c.Borrow(cduration_allocs)

	var cid_allocs *cgoAllocMap
	ref4f437f7c.id, cid_allocs = (C.uint64_t)(x.Id), cgoAllocsUnknown
	allocs4f437f7c.Borrow(cid_allocs)

	var cis_complete_allocs *cgoAllocMap
	ref4f437f7c.is_complete, cis_complete_allocs = (C.int8_t)(x.IsComplete), cgoAllocsUnknown
	allocs4f437f7c.Borrow(cis_complete_allocs)

	var cis_updated_allocs *cgoAllocMap
	ref4f437f7c.is_updated, cis_updated_allocs = (C.int8_t)(x.IsUpdated), cgoAllocsUnknown
	allocs4f437f7c.Borrow(cis_updated_allocs)

	var cis_new_allocs *cgoAllocMap
	ref4f437f7c.is_new, cis_new_allocs = (C.int8_t)(x.IsNew), cgoAllocsUnknown
	allocs4f437f7c.Borrow(cis_new_allocs)

	var chas_text_changed_allocs *cgoAllocMap
	ref4f437f7c.has_text_changed, chas_text_changed_allocs = (C.int8_t)(x.HasTextChanged), cgoAllocsUnknown
	allocs4f437f7c.Borrow(chas_text_changed_allocs)

	var chave_speakers_changed_allocs *cgoAllocMap
	ref4f437f7c.have_speakers_changed, chave_speakers_changed_allocs = (C.int8_t)(x.HaveSpeakersChanged), cgoAllocsUnknown
	allocs4f437f7c.Borrow(chave_speakers_changed_allocs)

	var cspeaker_spans_allocs *cgoAllocMap
	ref4f437f7c.speaker_spans, cspeaker_spans_allocs = unpackSSpeakerSpanT(x.SpeakerSpans)
	allocs4f437f7c.Borrow(cspeaker_spans_allocs)

	var cspeaker_span_count_allocs *cgoAllocMap
	ref4f437f7c.speaker_span_count, cspeaker_span_count_allocs = (C.uint64_t)(x.SpeakerSpanCount), cgoAllocsUnknown
	allocs4f437f7c.Borrow(cspeaker_span_count_allocs)

	var clast_transcription_latency_ms_allocs *cgoAllocMap
	ref4f437f7c.last_transcription_latency_ms, clast_transcription_latency_ms_allocs = (C.uint32_t)(x.LastTranscriptionLatencyMs), cgoAllocsUnknown
	allocs4f437f7c.Borrow(clast_transcription_latency_ms_allocs)

	var cwords_allocs *cgoAllocMap
	ref4f437f7c.words, cwords_allocs = unpackSTranscriptWordT(x.Words)
	allocs4f437f7c.Borrow(cwords_allocs)

	var cword_count_allocs *cgoAllocMap
	ref4f437f7c.word_count, cword_count_allocs = (C.uint64_t)(x.WordCount), cgoAllocsUnknown
	allocs4f437f7c.Borrow(cword_count_allocs)

	x.ref4f437f7c = ref4f437f7c
	x.allocs4f437f7c = allocs4f437f7c
	return ref4f437f7c, allocs4f437f7c

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x TranscriptLineT) PassValue() (C.struct_transcript_line_t, *cgoAllocMap) {
	if x.ref4f437f7c != nil {
		return *x.ref4f437f7c, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *TranscriptLineT) Deref() {
	if x.ref4f437f7c == nil {
		return
	}
	hxfa9955c := (*sliceHeader)(unsafe.Pointer(&x.Text))
	hxfa9955c.Data = unsafe.Pointer(x.ref4f437f7c.text)
	hxfa9955c.Cap = 0x7fffffff
	// hxfa9955c.Len = ? x.Text x.ref4f437f7c.text

	hxfa3f05c := (*sliceHeader)(unsafe.Pointer(&x.AudioData))
	hxfa3f05c.Data = unsafe.Pointer(x.ref4f437f7c.audio_data)
	hxfa3f05c.Cap = 0x7fffffff
	// hxfa3f05c.Len = ? x.AudioData x.ref4f437f7c.audio_data

	x.AudioDataCount = (uint64)(x.ref4f437f7c.audio_data_count)
	x.StartTime = (float32)(x.ref4f437f7c.start_time)
	x.Duration = (float32)(x.ref4f437f7c.duration)
	x.Id = (uint64)(x.ref4f437f7c.id)
	x.IsComplete = (int8)(x.ref4f437f7c.is_complete)
	x.IsUpdated = (int8)(x.ref4f437f7c.is_updated)
	x.IsNew = (int8)(x.ref4f437f7c.is_new)
	x.HasTextChanged = (int8)(x.ref4f437f7c.has_text_changed)
	x.HaveSpeakersChanged = (int8)(x.ref4f437f7c.have_speakers_changed)
	packSSpeakerSpanT(x.SpeakerSpans, x.ref4f437f7c.speaker_spans)
	x.SpeakerSpanCount = (uint64)(x.ref4f437f7c.speaker_span_count)
	x.LastTranscriptionLatencyMs = (uint32)(x.ref4f437f7c.last_transcription_latency_ms)
	packSTranscriptWordT(x.Words, x.ref4f437f7c.words)
	x.WordCount = (uint64)(x.ref4f437f7c.word_count)
}

// allocStructTranscriptTMemory allocates memory for type C.struct_transcript_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStructTranscriptTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStructTranscriptTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStructTranscriptTValue = unsafe.Sizeof([1]C.struct_transcript_t{})

// unpackSTranscriptLineT transforms a sliced Go data structure into plain C format.
func unpackSTranscriptLineT(x []TranscriptLineT) (unpacked *C.struct_transcript_line_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStructTranscriptLineTMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.struct_transcript_line_t)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.struct_transcript_line_t)(h.Data)
	return
}

// packSTranscriptLineT reads sliced Go data structure out from plain C format.
func packSTranscriptLineT(v []TranscriptLineT, ptr0 *C.struct_transcript_line_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStructTranscriptLineTValue]C.struct_transcript_line_t)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewTranscriptLineTRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *TranscriptT) Ref() *C.struct_transcript_t {
	if x == nil {
		return nil
	}
	return x.reff65a4ca6
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *TranscriptT) Free() {
	if x != nil && x.allocsf65a4ca6 != nil {
		x.allocsf65a4ca6.(*cgoAllocMap).Free()
		x.reff65a4ca6 = nil
	}
}

// NewTranscriptTRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewTranscriptTRef(ref unsafe.Pointer) *TranscriptT {
	if ref == nil {
		return nil
	}
	obj := new(TranscriptT)
	obj.reff65a4ca6 = (*C.struct_transcript_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *TranscriptT) PassRef() (*C.struct_transcript_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.reff65a4ca6 != nil {
		return x.reff65a4ca6, nil
	}
	memf65a4ca6 := allocStructTranscriptTMemory(1)
	reff65a4ca6 := (*C.struct_transcript_t)(memf65a4ca6)
	allocsf65a4ca6 := new(cgoAllocMap)
	allocsf65a4ca6.Add(memf65a4ca6)

	var clines_allocs *cgoAllocMap
	reff65a4ca6.lines, clines_allocs = unpackSTranscriptLineT(x.Lines)
	allocsf65a4ca6.Borrow(clines_allocs)

	var cline_count_allocs *cgoAllocMap
	reff65a4ca6.line_count, cline_count_allocs = (C.uint64_t)(x.LineCount), cgoAllocsUnknown
	allocsf65a4ca6.Borrow(cline_count_allocs)

	x.reff65a4ca6 = reff65a4ca6
	x.allocsf65a4ca6 = allocsf65a4ca6
	return reff65a4ca6, allocsf65a4ca6

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x TranscriptT) PassValue() (C.struct_transcript_t, *cgoAllocMap) {
	if x.reff65a4ca6 != nil {
		return *x.reff65a4ca6, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *TranscriptT) Deref() {
	if x.reff65a4ca6 == nil {
		return
	}
	packSTranscriptLineT(x.Lines, x.reff65a4ca6.lines)
	x.LineCount = (uint64)(x.reff65a4ca6.line_count)
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *TranscriptWordT) Ref() *C.struct_transcript_word_t {
	if x == nil {
		return nil
	}
	return x.refb21ffa94
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *TranscriptWordT) Free() {
	if x != nil && x.allocsb21ffa94 != nil {
		x.allocsb21ffa94.(*cgoAllocMap).Free()
		x.refb21ffa94 = nil
	}
}

// NewTranscriptWordTRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewTranscriptWordTRef(ref unsafe.Pointer) *TranscriptWordT {
	if ref == nil {
		return nil
	}
	obj := new(TranscriptWordT)
	obj.refb21ffa94 = (*C.struct_transcript_word_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *TranscriptWordT) PassRef() (*C.struct_transcript_word_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.refb21ffa94 != nil {
		return x.refb21ffa94, nil
	}
	memb21ffa94 := allocStructTranscriptWordTMemory(1)
	refb21ffa94 := (*C.struct_transcript_word_t)(memb21ffa94)
	allocsb21ffa94 := new(cgoAllocMap)
	allocsb21ffa94.Add(memb21ffa94)

	var ctext_allocs *cgoAllocMap
	refb21ffa94.text, ctext_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Text)))
	allocsb21ffa94.Borrow(ctext_allocs)

	var cstart_allocs *cgoAllocMap
	refb21ffa94.start, cstart_allocs = (C.float)(x.Start), cgoAllocsUnknown
	allocsb21ffa94.Borrow(cstart_allocs)

	var cend_allocs *cgoAllocMap
	refb21ffa94.end, cend_allocs = (C.float)(x.End), cgoAllocsUnknown
	allocsb21ffa94.Borrow(cend_allocs)

	var cconfidence_allocs *cgoAllocMap
	refb21ffa94.confidence, cconfidence_allocs = (C.float)(x.Confidence), cgoAllocsUnknown
	allocsb21ffa94.Borrow(cconfidence_allocs)

	x.refb21ffa94 = refb21ffa94
	x.allocsb21ffa94 = allocsb21ffa94
	return refb21ffa94, allocsb21ffa94

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x TranscriptWordT) PassValue() (C.struct_transcript_word_t, *cgoAllocMap) {
	if x.refb21ffa94 != nil {
		return *x.refb21ffa94, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *TranscriptWordT) Deref() {
	if x.refb21ffa94 == nil {
		return
	}
	hxf0d18b7 := (*sliceHeader)(unsafe.Pointer(&x.Text))
	hxf0d18b7.Data = unsafe.Pointer(x.refb21ffa94.text)
	hxf0d18b7.Cap = 0x7fffffff
	// hxf0d18b7.Len = ? x.Text x.refb21ffa94.text

	x.Start = (float32)(x.refb21ffa94.start)
	x.End = (float32)(x.refb21ffa94.end)
	x.Confidence = (float32)(x.refb21ffa94.confidence)
}

// unpackArgSTranscriptT transforms a sliced Go data structure into plain C format.
func unpackArgSTranscriptT(x []TranscriptT) (unpacked *C.struct_transcript_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStructTranscriptTMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.struct_transcript_t)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.struct_transcript_t)(h.Data)
	return
}

// packSTranscriptT reads sliced Go data structure out from plain C format.
func packSTranscriptT(v []TranscriptT, ptr0 *C.struct_transcript_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStructTranscriptTValue]C.struct_transcript_t)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewTranscriptTRef(unsafe.Pointer(&ptr1))
	}
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}

// unpackArgSMoonshineOptionT transforms a sliced Go data structure into plain C format.
func unpackArgSMoonshineOptionT(x []MoonshineOptionT) (unpacked *C.struct_moonshine_option_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStructMoonshineOptionTMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.struct_moonshine_option_t)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.struct_moonshine_option_t)(h.Data)
	return
}

// packSMoonshineOptionT reads sliced Go data structure out from plain C format.
func packSMoonshineOptionT(v []MoonshineOptionT, ptr0 *C.struct_moonshine_option_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStructMoonshineOptionTValue]C.struct_moonshine_option_t)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewMoonshineOptionTRef(unsafe.Pointer(&ptr1))
	}
}

// copyPUint8TBytes copies the data from Go slice as *C.uint8_t.
func copyPUint8TBytes(slice *sliceHeader) (*C.uint8_t, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfUint8TValue) * slice.Len,
		Cap:  int(sizeOfUint8TValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.uint8_t)(mem0), allocs
}

// allocUint8TMemory allocates memory for type C.uint8_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocUint8TMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfUint8TValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfUint8TValue = unsafe.Sizeof([1]C.uint8_t{})

// allocPCharMemory allocates memory for type *C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPCharValue = unsafe.Sizeof([1]*C.char{})

// unpackArgSString transforms a sliced Go data structure into plain C format.
func unpackArgSString(x []string) (unpacked **C.char, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocPCharMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.char)(unsafe.Pointer(h0))
	for i0 := range x {
		v0[i0], _ = unpackPCharString(x[i0])
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.char)(h.Data)
	return
}

// packSString reads sliced Go data structure out from plain C format.
func packSString(v []string, ptr0 **C.char) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.char)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = packPCharString(ptr1)
	}
}

// packPCharString creates a Go string backed by *C.char and avoids copying.
func packPCharString(p *C.char) (raw string) {
	if p != nil && *p != 0 {
		h := (*stringHeader)(unsafe.Pointer(&raw))
		h.Data = unsafe.Pointer(p)
		for *p != 0 {
			p = (*C.char)(unsafe.Pointer(uintptr(unsafe.Pointer(p)) + 1)) // p++
		}
		h.Len = int(uintptr(unsafe.Pointer(p)) - uintptr(h.Data))
	}
	return
}

// RawString reperesents a string backed by data on the C side.
type RawString string

// Copy returns a Go-managed copy of raw string.
func (raw RawString) Copy() string {
	if len(raw) == 0 {
		return ""
	}
	h := (*stringHeader)(unsafe.Pointer(&raw))
	return C.GoStringN((*C.char)(h.Data), C.int(h.Len))
}

// allocPUint8TMemory allocates memory for type *C.uint8_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPUint8TMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPUint8TValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPUint8TValue = unsafe.Sizeof([1]*C.uint8_t{})

// unpackArgSSByte transforms a sliced Go data structure into plain C format.
func unpackArgSSByte(x [][]byte) (unpacked **C.uint8_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocPUint8TMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.uint8_t)(unsafe.Pointer(h0))
	for i0 := range x {
		h := (*sliceHeader)(unsafe.Pointer(&x[i0]))
		v0[i0] = (*C.uint8_t)(h.Data)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.uint8_t)(h.Data)
	return
}

// packSSByte reads sliced Go data structure out from plain C format.
func packSSByte(v [][]byte, ptr0 **C.uint8_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.uint8_t)(unsafe.Pointer(ptr0)))[i0]
		hxf2fab0d := (*sliceHeader)(unsafe.Pointer(&v[i0]))
		hxf2fab0d.Data = unsafe.Pointer(ptr1)
		hxf2fab0d.Cap = 0x7fffffff
		// hxf2fab0d.Len = ?
	}
}

// copyPUint64TBytes copies the data from Go slice as *C.uint64_t.
func copyPUint64TBytes(slice *sliceHeader) (*C.uint64_t, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfUint64TValue) * slice.Len,
		Cap:  int(sizeOfUint64TValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.uint64_t)(mem0), allocs
}

// allocUint64TMemory allocates memory for type C.uint64_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocUint64TMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfUint64TValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfUint64TValue = unsafe.Sizeof([1]C.uint64_t{})

// allocPStructTranscriptTMemory allocates memory for type *C.struct_transcript_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPStructTranscriptTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPStructTranscriptTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPStructTranscriptTValue = unsafe.Sizeof([1]*C.struct_transcript_t{})

// unpackArgSSTranscriptT transforms a sliced Go data structure into plain C format.
func unpackArgSSTranscriptT(x [][]TranscriptT) (unpacked **C.struct_transcript_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocPStructTranscriptTMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.struct_transcript_t)(unsafe.Pointer(h0))
	for i0 := range x {
		len1 := len(x[i0])
		mem1 := allocStructTranscriptTMemory(len1)
		allocs.Add(mem1)
		h1 := &sliceHeader{
			Data: mem1,
			Cap:  len1,
			Len:  len1,
		}
		v1 := *(*[]C.struct_transcript_t)(unsafe.Pointer(h1))
		for i1 := range x[i0] {
			allocs1 := new(cgoAllocMap)
			v1[i1], allocs1 = x[i0][i1].PassValue()
			allocs.Borrow(allocs1)
		}
		h := (*sliceHeader)(unsafe.Pointer(&v1))
		v0[i0] = (*C.struct_transcript_t)(h.Data)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.struct_transcript_t)(h.Data)
	return
}

// packSSTranscriptT reads sliced Go data structure out from plain C format.
func packSSTranscriptT(v [][]TranscriptT, ptr0 **C.struct_transcript_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.struct_transcript_t)(unsafe.Pointer(ptr0)))[i0]
		for i1 := range v[i0] {
			ptr2 := (*(*[m / sizeOfStructTranscriptTValue]C.struct_transcript_t)(unsafe.Pointer(ptr1)))[i1]
			v[i0][i1] = *NewTranscriptTRef(unsafe.Pointer(&ptr2))
		}
	}
}

// allocPFloatMemory allocates memory for type *C.float in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPFloatMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPFloatValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPFloatValue = unsafe.Sizeof([1]*C.float{})

// unpackArgSSFloat32 transforms a sliced Go data structure into plain C format.
func unpackArgSSFloat32(x [][]float32) (unpacked **C.float, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocPFloatMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.float)(unsafe.Pointer(h0))
	for i0 := range x {
		h := (*sliceHeader)(unsafe.Pointer(&x[i0]))
		v0[i0] = (*C.float)(h.Data)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.float)(h.Data)
	return
}

// packSSFloat32 reads sliced Go data structure out from plain C format.
func packSSFloat32(v [][]float32, ptr0 **C.float) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.float)(unsafe.Pointer(ptr0)))[i0]
		hxf65bf54 := (*sliceHeader)(unsafe.Pointer(&v[i0]))
		hxf65bf54.Data = unsafe.Pointer(ptr1)
		hxf65bf54.Cap = 0x7fffffff
		// hxf65bf54.Len = ?
	}
}

// unpackArgSMoonshineSpeechClipT transforms a sliced Go data structure into plain C format.
func unpackArgSMoonshineSpeechClipT(x []MoonshineSpeechClipT) (unpacked *C.struct_moonshine_speech_clip_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStructMoonshineSpeechClipTMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.struct_moonshine_speech_clip_t)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.struct_moonshine_speech_clip_t)(h.Data)
	return
}

// packSMoonshineSpeechClipT reads sliced Go data structure out from plain C format.
func packSMoonshineSpeechClipT(v []MoonshineSpeechClipT, ptr0 *C.struct_moonshine_speech_clip_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStructMoonshineSpeechClipTValue]C.struct_moonshine_speech_clip_t)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewMoonshineSpeechClipTRef(unsafe.Pointer(&ptr1))
	}
}

// copyPInt32TBytes copies the data from Go slice as *C.int32_t.
func copyPInt32TBytes(slice *sliceHeader) (*C.int32_t, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfInt32TValue) * slice.Len,
		Cap:  int(sizeOfInt32TValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.int32_t)(mem0), allocs
}

// allocInt32TMemory allocates memory for type C.int32_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocInt32TMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfInt32TValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfInt32TValue = unsafe.Sizeof([1]C.int32_t{})
