// Copyright 2025 Moonshine AI
// 
// SPDX-License-Identifier: MIT
// 

// WARNING: This file has automatically been generated 
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "moonshine-c-api.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

