// Copyright 2025 Moonshine AI
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../core
#cgo LDFLAGS: -L${SRCDIR}/../../../core/build -lmoonshine
#include "moonshine-c-api.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// MoonshineHeaderVersion as defined in core/moonshine-c-api.h:95
	MoonshineHeaderVersion = (30000)
	// MoonshineFromMemoryRemovedVersion as defined in core/moonshine-c-api.h:104
	MoonshineFromMemoryRemovedVersion = (30000)
	// MoonshineModelArchTiny as defined in core/moonshine-c-api.h:107
	MoonshineModelArchTiny = (0)
	// MoonshineModelArchBase as defined in core/moonshine-c-api.h:108
	MoonshineModelArchBase = (1)
	// MoonshineModelArchTinyStreaming as defined in core/moonshine-c-api.h:109
	MoonshineModelArchTinyStreaming = (2)
	// MoonshineModelArchBaseStreaming as defined in core/moonshine-c-api.h:110
	MoonshineModelArchBaseStreaming = (3)
	// MoonshineModelArchSmallStreaming as defined in core/moonshine-c-api.h:111
	MoonshineModelArchSmallStreaming = (4)
	// MoonshineModelArchMediumStreaming as defined in core/moonshine-c-api.h:112
	MoonshineModelArchMediumStreaming = (5)
	// MoonshineErrorNone as defined in core/moonshine-c-api.h:115
	MoonshineErrorNone = (0)
	// MoonshineErrorUnknown as defined in core/moonshine-c-api.h:116
	MoonshineErrorUnknown = (-1)
	// MoonshineErrorInvalidHandle as defined in core/moonshine-c-api.h:117
	MoonshineErrorInvalidHandle = (-2)
	// MoonshineErrorInvalidArgument as defined in core/moonshine-c-api.h:118
	MoonshineErrorInvalidArgument = (-3)
	// MoonshineFlagForceUpdate as defined in core/moonshine-c-api.h:121
	MoonshineFlagForceUpdate = (1 << 0)
	// MoonshineFlagSpellingMode as defined in core/moonshine-c-api.h:135
	MoonshineFlagSpellingMode = (1 << 1)
	// MoonshineEmbeddingModelArchGemma300m as defined in core/moonshine-c-api.h:686
	MoonshineEmbeddingModelArchGemma300m = (0)
)
