// Copyright 2025 Moonshine AI
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package raw provides generated low-level bindings to the Moonshine C API.
*/
package raw
