// Copyright 2025 Moonshine AI
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../core
#cgo LDFLAGS: -L${SRCDIR}/../../../core/build -lmoonshine
#include "moonshine-c-api.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// MoonshineGetVersion function as declared in core/moonshine-c-api.h:295
func MoonshineGetVersion() int32 {
	__ret := C.moonshine_get_version()
	__v := (int32)(__ret)
	return __v
}

// MoonshineErrorToString function as declared in core/moonshine-c-api.h:299
func MoonshineErrorToString(Error int32) *byte {
	cError, cErrorAllocMap := (C.int32_t)(Error), cgoAllocsUnknown
	__ret := C.moonshine_error_to_string(cError)
	runtime.KeepAlive(cErrorAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// MoonshineFreeBuffer function as declared in core/moonshine-c-api.h:315
func MoonshineFreeBuffer(Ptr unsafe.Pointer) {
	cPtr, cPtrAllocMap := Ptr, cgoAllocsUnknown
	C.moonshine_free_buffer(cPtr)
	runtime.KeepAlive(cPtrAllocMap)
}

// MoonshineTranscriptToString function as declared in core/moonshine-c-api.h:320
func MoonshineTranscriptToString(Transcript []TranscriptT) *byte {
	cTranscript, cTranscriptAllocMap := unpackArgSTranscriptT(Transcript)
	__ret := C.moonshine_transcript_to_string(cTranscript)
	packSTranscriptT(Transcript, cTranscript)
	runtime.KeepAlive(cTranscriptAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// MoonshineLoadTranscriberFromFiles function as declared in core/moonshine-c-api.h:387
func MoonshineLoadTranscriberFromFiles(Path string, ModelArch uint32, Options []MoonshineOptionT, OptionsCount uint64, MoonshineVersion int32) int32 {
	cPath, cPathAllocMap := unpackPCharString(Path)
	cModelArch, cModelArchAllocMap := (C.uint32_t)(ModelArch), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cMoonshineVersion, cMoonshineVersionAllocMap := (C.int32_t)(MoonshineVersion), cgoAllocsUnknown
	__ret := C.moonshine_load_transcriber_from_files(cPath, cModelArch, cOptions, cOptionsCount, cMoonshineVersion)
	runtime.KeepAlive(cMoonshineVersionAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cModelArchAllocMap)
	runtime.KeepAlive(cPathAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineLoadTranscriberFromMemory function as declared in core/moonshine-c-api.h:416
func MoonshineLoadTranscriberFromMemory(EncoderModelData []byte, EncoderModelDataSize uint64, DecoderModelData []byte, DecoderModelDataSize uint64, TokenizerData []byte, TokenizerDataSize uint64, SpellingModelData []byte, SpellingModelDataSize uint64, ModelArch uint32, Options []MoonshineOptionT, OptionsCount uint64, MoonshineVersion int32) int32 {
	cEncoderModelData, cEncoderModelDataAllocMap := (*C.uint8_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&EncoderModelData)).Data)), cgoAllocsUnknown
	cEncoderModelDataSize, cEncoderModelDataSizeAllocMap := (C.size_t)(EncoderModelDataSize), cgoAllocsUnknown
	cDecoderModelData, cDecoderModelDataAllocMap := (*C.uint8_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&DecoderModelData)).Data)), cgoAllocsUnknown
	cDecoderModelDataSize, cDecoderModelDataSizeAllocMap := (C.size_t)(DecoderModelDataSize), cgoAllocsUnknown
	cTokenizerData, cTokenizerDataAllocMap := (*C.uint8_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&TokenizerData)).Data)), cgoAllocsUnknown
	cTokenizerDataSize, cTokenizerDataSizeAllocMap := (C.size_t)(TokenizerDataSize), cgoAllocsUnknown
	cSpellingModelData, cSpellingModelDataAllocMap := (*C.uint8_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&SpellingModelData)).Data)), cgoAllocsUnknown
	cSpellingModelDataSize, cSpellingModelDataSizeAllocMap := (C.size_t)(SpellingModelDataSize), cgoAllocsUnknown
	cModelArch, cModelArchAllocMap := (C.uint32_t)(ModelArch), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cMoonshineVersion, cMoonshineVersionAllocMap := (C.int32_t)(MoonshineVersion), cgoAllocsUnknown
	__ret := C.moonshine_load_transcriber_from_memory(cEncoderModelData, cEncoderModelDataSize, cDecoderModelData, cDecoderModelDataSize, cTokenizerData, cTokenizerDataSize, cSpellingModelData, cSpellingModelDataSize, cModelArch, cOptions, cOptionsCount, cMoonshineVersion)
	runtime.KeepAlive(cMoonshineVersionAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cModelArchAllocMap)
	runtime.KeepAlive(cSpellingModelDataSizeAllocMap)
	runtime.KeepAlive(cSpellingModelDataAllocMap)
	runtime.KeepAlive(cTokenizerDataSizeAllocMap)
	runtime.KeepAlive(cTokenizerDataAllocMap)
	runtime.KeepAlive(cDecoderModelDataSizeAllocMap)
	runtime.KeepAlive(cDecoderModelDataAllocMap)
	runtime.KeepAlive(cEncoderModelDataSizeAllocMap)
	runtime.KeepAlive(cEncoderModelDataAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineLoadTranscriberFromMemoryFiles function as declared in core/moonshine-c-api.h:461
func MoonshineLoadTranscriberFromMemoryFiles(Filenames []string, Memory [][]byte, MemorySizes []uint64, FileCount uint64, ModelArch uint32, Options []MoonshineOptionT, OptionsCount uint64, MoonshineVersion int32) int32 {
	cFilenames, cFilenamesAllocMap := unpackArgSString(Filenames)
	cMemory, cMemoryAllocMap := unpackArgSSByte(Memory)
	cMemorySizes, cMemorySizesAllocMap := (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&MemorySizes)).Data)), cgoAllocsUnknown
	cFileCount, cFileCountAllocMap := (C.uint64_t)(FileCount), cgoAllocsUnknown
	cModelArch, cModelArchAllocMap := (C.uint32_t)(ModelArch), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cMoonshineVersion, cMoonshineVersionAllocMap := (C.int32_t)(MoonshineVersion), cgoAllocsUnknown
	__ret := C.moonshine_load_transcriber_from_memory_files(cFilenames, cMemory, cMemorySizes, cFileCount, cModelArch, cOptions, cOptionsCount, cMoonshineVersion)
	runtime.KeepAlive(cMoonshineVersionAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cModelArchAllocMap)
	runtime.KeepAlive(cFileCountAllocMap)
	runtime.KeepAlive(cMemorySizesAllocMap)
	packSSByte(Memory, cMemory)
	runtime.KeepAlive(cMemoryAllocMap)
	packSString(Filenames, cFilenames)
	runtime.KeepAlive(cFilenamesAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineFreeTranscriber function as declared in core/moonshine-c-api.h:470
func MoonshineFreeTranscriber(TranscriberHandle int32) {
	cTranscriberHandle, cTranscriberHandleAllocMap := (C.int32_t)(TranscriberHandle), cgoAllocsUnknown
	C.moonshine_free_transcriber(cTranscriberHandle)
	runtime.KeepAlive(cTranscriberHandleAllocMap)
}

// MoonshineTranscribeWithoutStreaming function as declared in core/moonshine-c-api.h:507
func MoonshineTranscribeWithoutStreaming(TranscriberHandle int32, AudioData []float32, AudioLength uint64, SampleRate int32, Flags uint32, OutTranscript [][]TranscriptT) int32 {
	cTranscriberHandle, cTranscriberHandleAllocMap := (C.int32_t)(TranscriberHandle), cgoAllocsUnknown
	cAudioData, cAudioDataAllocMap := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&AudioData)).Data)), cgoAllocsUnknown
	cAudioLength, cAudioLengthAllocMap := (C.uint64_t)(AudioLength), cgoAllocsUnknown
	cSampleRate, cSampleRateAllocMap := (C.int32_t)(SampleRate), cgoAllocsUnknown
	cFlags, cFlagsAllocMap := (C.uint32_t)(Flags), cgoAllocsUnknown
	cOutTranscript, cOutTranscriptAllocMap := unpackArgSSTranscriptT(OutTranscript)
	__ret := C.moonshine_transcribe_without_streaming(cTranscriberHandle, cAudioData, cAudioLength, cSampleRate, cFlags, cOutTranscript)
	packSSTranscriptT(OutTranscript, cOutTranscript)
	runtime.KeepAlive(cOutTranscriptAllocMap)
	runtime.KeepAlive(cFlagsAllocMap)
	runtime.KeepAlive(cSampleRateAllocMap)
	runtime.KeepAlive(cAudioLengthAllocMap)
	runtime.KeepAlive(cAudioDataAllocMap)
	runtime.KeepAlive(cTranscriberHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineCreateStream function as declared in core/moonshine-c-api.h:589
func MoonshineCreateStream(TranscriberHandle int32, Flags uint32) int32 {
	cTranscriberHandle, cTranscriberHandleAllocMap := (C.int32_t)(TranscriberHandle), cgoAllocsUnknown
	cFlags, cFlagsAllocMap := (C.uint32_t)(Flags), cgoAllocsUnknown
	__ret := C.moonshine_create_stream(cTranscriberHandle, cFlags)
	runtime.KeepAlive(cFlagsAllocMap)
	runtime.KeepAlive(cTranscriberHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineFreeStream function as declared in core/moonshine-c-api.h:595
func MoonshineFreeStream(TranscriberHandle int32, StreamHandle int32) int32 {
	cTranscriberHandle, cTranscriberHandleAllocMap := (C.int32_t)(TranscriberHandle), cgoAllocsUnknown
	cStreamHandle, cStreamHandleAllocMap := (C.int32_t)(StreamHandle), cgoAllocsUnknown
	__ret := C.moonshine_free_stream(cTranscriberHandle, cStreamHandle)
	runtime.KeepAlive(cStreamHandleAllocMap)
	runtime.KeepAlive(cTranscriberHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineStartStream function as declared in core/moonshine-c-api.h:606
func MoonshineStartStream(TranscriberHandle int32, StreamHandle int32) int32 {
	cTranscriberHandle, cTranscriberHandleAllocMap := (C.int32_t)(TranscriberHandle), cgoAllocsUnknown
	cStreamHandle, cStreamHandleAllocMap := (C.int32_t)(StreamHandle), cgoAllocsUnknown
	__ret := C.moonshine_start_stream(cTranscriberHandle, cStreamHandle)
	runtime.KeepAlive(cStreamHandleAllocMap)
	runtime.KeepAlive(cTranscriberHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineStopStream function as declared in core/moonshine-c-api.h:613
func MoonshineStopStream(TranscriberHandle int32, StreamHandle int32) int32 {
	cTranscriberHandle, cTranscriberHandleAllocMap := (C.int32_t)(TranscriberHandle), cgoAllocsUnknown
	cStreamHandle, cStreamHandleAllocMap := (C.int32_t)(StreamHandle), cgoAllocsUnknown
	__ret := C.moonshine_stop_stream(cTranscriberHandle, cStreamHandle)
	runtime.KeepAlive(cStreamHandleAllocMap)
	runtime.KeepAlive(cTranscriberHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineTranscribeAddAudioToStream function as declared in core/moonshine-c-api.h:646
func MoonshineTranscribeAddAudioToStream(TranscriberHandle int32, StreamHandle int32, NewAudioData []float32, AudioLength uint64, SampleRate int32, Flags uint32) int32 {
	cTranscriberHandle, cTranscriberHandleAllocMap := (C.int32_t)(TranscriberHandle), cgoAllocsUnknown
	cStreamHandle, cStreamHandleAllocMap := (C.int32_t)(StreamHandle), cgoAllocsUnknown
	cNewAudioData, cNewAudioDataAllocMap := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&NewAudioData)).Data)), cgoAllocsUnknown
	cAudioLength, cAudioLengthAllocMap := (C.uint64_t)(AudioLength), cgoAllocsUnknown
	cSampleRate, cSampleRateAllocMap := (C.int32_t)(SampleRate), cgoAllocsUnknown
	cFlags, cFlagsAllocMap := (C.uint32_t)(Flags), cgoAllocsUnknown
	__ret := C.moonshine_transcribe_add_audio_to_stream(cTranscriberHandle, cStreamHandle, cNewAudioData, cAudioLength, cSampleRate, cFlags)
	runtime.KeepAlive(cFlagsAllocMap)
	runtime.KeepAlive(cSampleRateAllocMap)
	runtime.KeepAlive(cAudioLengthAllocMap)
	runtime.KeepAlive(cNewAudioDataAllocMap)
	runtime.KeepAlive(cStreamHandleAllocMap)
	runtime.KeepAlive(cTranscriberHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineTranscribeStream function as declared in core/moonshine-c-api.h:679
func MoonshineTranscribeStream(TranscriberHandle int32, StreamHandle int32, Flags uint32, OutTranscript [][]TranscriptT) int32 {
	cTranscriberHandle, cTranscriberHandleAllocMap := (C.int32_t)(TranscriberHandle), cgoAllocsUnknown
	cStreamHandle, cStreamHandleAllocMap := (C.int32_t)(StreamHandle), cgoAllocsUnknown
	cFlags, cFlagsAllocMap := (C.uint32_t)(Flags), cgoAllocsUnknown
	cOutTranscript, cOutTranscriptAllocMap := unpackArgSSTranscriptT(OutTranscript)
	__ret := C.moonshine_transcribe_stream(cTranscriberHandle, cStreamHandle, cFlags, cOutTranscript)
	packSSTranscriptT(OutTranscript, cOutTranscript)
	runtime.KeepAlive(cOutTranscriptAllocMap)
	runtime.KeepAlive(cFlagsAllocMap)
	runtime.KeepAlive(cStreamHandleAllocMap)
	runtime.KeepAlive(cTranscriberHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineCreateEmbeddingModel function as declared in core/moonshine-c-api.h:703
func MoonshineCreateEmbeddingModel(ModelPath string, ModelArch uint32, ModelVariant string) int32 {
	cModelPath, cModelPathAllocMap := unpackPCharString(ModelPath)
	cModelArch, cModelArchAllocMap := (C.uint32_t)(ModelArch), cgoAllocsUnknown
	cModelVariant, cModelVariantAllocMap := unpackPCharString(ModelVariant)
	__ret := C.moonshine_create_embedding_model(cModelPath, cModelArch, cModelVariant)
	runtime.KeepAlive(cModelVariantAllocMap)
	runtime.KeepAlive(cModelArchAllocMap)
	runtime.KeepAlive(cModelPathAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineCreateEmbeddingModelFromMemory function as declared in core/moonshine-c-api.h:725
func MoonshineCreateEmbeddingModelFromMemory(ModelArch uint32, ModelVariant string, Filenames []string, FilenamesCount uint64, Memory [][]byte, MemorySizes []uint64, Options []MoonshineOptionT, OptionsCount uint64, MoonshineVersion int32) int32 {
	cModelArch, cModelArchAllocMap := (C.uint32_t)(ModelArch), cgoAllocsUnknown
	cModelVariant, cModelVariantAllocMap := unpackPCharString(ModelVariant)
	cFilenames, cFilenamesAllocMap := unpackArgSString(Filenames)
	cFilenamesCount, cFilenamesCountAllocMap := (C.uint64_t)(FilenamesCount), cgoAllocsUnknown
	cMemory, cMemoryAllocMap := unpackArgSSByte(Memory)
	cMemorySizes, cMemorySizesAllocMap := (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&MemorySizes)).Data)), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cMoonshineVersion, cMoonshineVersionAllocMap := (C.int32_t)(MoonshineVersion), cgoAllocsUnknown
	__ret := C.moonshine_create_embedding_model_from_memory(cModelArch, cModelVariant, cFilenames, cFilenamesCount, cMemory, cMemorySizes, cOptions, cOptionsCount, cMoonshineVersion)
	runtime.KeepAlive(cMoonshineVersionAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cMemorySizesAllocMap)
	packSSByte(Memory, cMemory)
	runtime.KeepAlive(cMemoryAllocMap)
	runtime.KeepAlive(cFilenamesCountAllocMap)
	packSString(Filenames, cFilenames)
	runtime.KeepAlive(cFilenamesAllocMap)
	runtime.KeepAlive(cModelVariantAllocMap)
	runtime.KeepAlive(cModelArchAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineFreeEmbeddingModel function as declared in core/moonshine-c-api.h:732
func MoonshineFreeEmbeddingModel(EmbeddingModelHandle int32) {
	cEmbeddingModelHandle, cEmbeddingModelHandleAllocMap := (C.int32_t)(EmbeddingModelHandle), cgoAllocsUnknown
	C.moonshine_free_embedding_model(cEmbeddingModelHandle)
	runtime.KeepAlive(cEmbeddingModelHandleAllocMap)
}

// MoonshineCalculateEmbedding function as declared in core/moonshine-c-api.h:743
func MoonshineCalculateEmbedding(EmbeddingModelHandle int32, Sentence string, OutEmbedding [][]float32, OutEmbeddingSize []uint64, ModelName string) int32 {
	cEmbeddingModelHandle, cEmbeddingModelHandleAllocMap := (C.int32_t)(EmbeddingModelHandle), cgoAllocsUnknown
	cSentence, cSentenceAllocMap := unpackPCharString(Sentence)
	cOutEmbedding, cOutEmbeddingAllocMap := unpackArgSSFloat32(OutEmbedding)
	cOutEmbeddingSize, cOutEmbeddingSizeAllocMap := (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&OutEmbeddingSize)).Data)), cgoAllocsUnknown
	cModelName, cModelNameAllocMap := unpackPCharString(ModelName)
	__ret := C.moonshine_calculate_embedding(cEmbeddingModelHandle, cSentence, cOutEmbedding, cOutEmbeddingSize, cModelName)
	runtime.KeepAlive(cModelNameAllocMap)
	runtime.KeepAlive(cOutEmbeddingSizeAllocMap)
	packSSFloat32(OutEmbedding, cOutEmbedding)
	runtime.KeepAlive(cOutEmbeddingAllocMap)
	runtime.KeepAlive(cSentenceAllocMap)
	runtime.KeepAlive(cEmbeddingModelHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineFreeEmbedding function as declared in core/moonshine-c-api.h:748
func MoonshineFreeEmbedding(Embedding []float32) {
	cEmbedding, cEmbeddingAllocMap := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Embedding)).Data)), cgoAllocsUnknown
	C.moonshine_free_embedding(cEmbedding)
	runtime.KeepAlive(cEmbeddingAllocMap)
}

// MoonshineCalculateEmbeddingDistance function as declared in core/moonshine-c-api.h:758
func MoonshineCalculateEmbeddingDistance(EmbeddingModelHandle int32, EmbeddingA []float32, EmbeddingB []float32, EmbeddingSize uint64, OutSimilarity []float32) int32 {
	cEmbeddingModelHandle, cEmbeddingModelHandleAllocMap := (C.int32_t)(EmbeddingModelHandle), cgoAllocsUnknown
	cEmbeddingA, cEmbeddingAAllocMap := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&EmbeddingA)).Data)), cgoAllocsUnknown
	cEmbeddingB, cEmbeddingBAllocMap := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&EmbeddingB)).Data)), cgoAllocsUnknown
	cEmbeddingSize, cEmbeddingSizeAllocMap := (C.uint64_t)(EmbeddingSize), cgoAllocsUnknown
	cOutSimilarity, cOutSimilarityAllocMap := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&OutSimilarity)).Data)), cgoAllocsUnknown
	__ret := C.moonshine_calculate_embedding_distance(cEmbeddingModelHandle, cEmbeddingA, cEmbeddingB, cEmbeddingSize, cOutSimilarity)
	runtime.KeepAlive(cOutSimilarityAllocMap)
	runtime.KeepAlive(cEmbeddingSizeAllocMap)
	runtime.KeepAlive(cEmbeddingBAllocMap)
	runtime.KeepAlive(cEmbeddingAAllocMap)
	runtime.KeepAlive(cEmbeddingModelHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineExtractSpeechClip function as declared in core/moonshine-c-api.h:812
func MoonshineExtractSpeechClip(AudioData []float32, AudioLength uint64, SampleRate int32, TtsSynthesizerHandle int32, Options []MoonshineOptionT, OptionsCount uint64, OutClip []MoonshineSpeechClipT) int32 {
	cAudioData, cAudioDataAllocMap := (*C.float)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&AudioData)).Data)), cgoAllocsUnknown
	cAudioLength, cAudioLengthAllocMap := (C.uint64_t)(AudioLength), cgoAllocsUnknown
	cSampleRate, cSampleRateAllocMap := (C.int32_t)(SampleRate), cgoAllocsUnknown
	cTtsSynthesizerHandle, cTtsSynthesizerHandleAllocMap := (C.int32_t)(TtsSynthesizerHandle), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutClip, cOutClipAllocMap := unpackArgSMoonshineSpeechClipT(OutClip)
	__ret := C.moonshine_extract_speech_clip(cAudioData, cAudioLength, cSampleRate, cTtsSynthesizerHandle, cOptions, cOptionsCount, cOutClip)
	packSMoonshineSpeechClipT(OutClip, cOutClip)
	runtime.KeepAlive(cOutClipAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cTtsSynthesizerHandleAllocMap)
	runtime.KeepAlive(cSampleRateAllocMap)
	runtime.KeepAlive(cAudioLengthAllocMap)
	runtime.KeepAlive(cAudioDataAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineCreateTtsSynthesizerFromFiles function as declared in core/moonshine-c-api.h:849
func MoonshineCreateTtsSynthesizerFromFiles(Language string, Filenames []string, FilenamesCount uint64, Options []MoonshineOptionT, OptionsCount uint64, MoonshineVersion int32) int32 {
	cLanguage, cLanguageAllocMap := unpackPCharString(Language)
	cFilenames, cFilenamesAllocMap := unpackArgSString(Filenames)
	cFilenamesCount, cFilenamesCountAllocMap := (C.uint64_t)(FilenamesCount), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cMoonshineVersion, cMoonshineVersionAllocMap := (C.int32_t)(MoonshineVersion), cgoAllocsUnknown
	__ret := C.moonshine_create_tts_synthesizer_from_files(cLanguage, cFilenames, cFilenamesCount, cOptions, cOptionsCount, cMoonshineVersion)
	runtime.KeepAlive(cMoonshineVersionAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cFilenamesCountAllocMap)
	packSString(Filenames, cFilenames)
	runtime.KeepAlive(cFilenamesAllocMap)
	runtime.KeepAlive(cLanguageAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineCreateTtsSynthesizerFromMemory function as declared in core/moonshine-c-api.h:881
func MoonshineCreateTtsSynthesizerFromMemory(Language string, Filenames []string, FilenamesCount uint64, Memory [][]byte, MemorySizes []uint64, Options []MoonshineOptionT, OptionsCount uint64, MoonshineVersion int32) int32 {
	cLanguage, cLanguageAllocMap := unpackPCharString(Language)
	cFilenames, cFilenamesAllocMap := unpackArgSString(Filenames)
	cFilenamesCount, cFilenamesCountAllocMap := (C.uint64_t)(FilenamesCount), cgoAllocsUnknown
	cMemory, cMemoryAllocMap := unpackArgSSByte(Memory)
	cMemorySizes, cMemorySizesAllocMap := (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&MemorySizes)).Data)), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cMoonshineVersion, cMoonshineVersionAllocMap := (C.int32_t)(MoonshineVersion), cgoAllocsUnknown
	__ret := C.moonshine_create_tts_synthesizer_from_memory(cLanguage, cFilenames, cFilenamesCount, cMemory, cMemorySizes, cOptions, cOptionsCount, cMoonshineVersion)
	runtime.KeepAlive(cMoonshineVersionAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cMemorySizesAllocMap)
	packSSByte(Memory, cMemory)
	runtime.KeepAlive(cMemoryAllocMap)
	runtime.KeepAlive(cFilenamesCountAllocMap)
	packSString(Filenames, cFilenames)
	runtime.KeepAlive(cFilenamesAllocMap)
	runtime.KeepAlive(cLanguageAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineFreeTtsSynthesizer function as declared in core/moonshine-c-api.h:890
func MoonshineFreeTtsSynthesizer(TtsSynthesizerHandle int32) {
	cTtsSynthesizerHandle, cTtsSynthesizerHandleAllocMap := (C.int32_t)(TtsSynthesizerHandle), cgoAllocsUnknown
	C.moonshine_free_tts_synthesizer(cTtsSynthesizerHandle)
	runtime.KeepAlive(cTtsSynthesizerHandleAllocMap)
}

// MoonshineGetG2pDependencies function as declared in core/moonshine-c-api.h:910
func MoonshineGetG2pDependencies(Languages string, Options []MoonshineOptionT, OptionsCount uint64, OutDependenciesJson **byte) int32 {
	cLanguages, cLanguagesAllocMap := unpackPCharString(Languages)
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutDependenciesJson, cOutDependenciesJsonAllocMap := (**C.char)(unsafe.Pointer(OutDependenciesJson)), cgoAllocsUnknown
	__ret := C.moonshine_get_g2p_dependencies(cLanguages, cOptions, cOptionsCount, cOutDependenciesJson)
	runtime.KeepAlive(cOutDependenciesJsonAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cLanguagesAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineGetTtsDependencies function as declared in core/moonshine-c-api.h:934
func MoonshineGetTtsDependencies(Languages string, Options []MoonshineOptionT, OptionsCount uint64, OutDependenciesJson **byte) int32 {
	cLanguages, cLanguagesAllocMap := unpackPCharString(Languages)
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutDependenciesJson, cOutDependenciesJsonAllocMap := (**C.char)(unsafe.Pointer(OutDependenciesJson)), cgoAllocsUnknown
	__ret := C.moonshine_get_tts_dependencies(cLanguages, cOptions, cOptionsCount, cOutDependenciesJson)
	runtime.KeepAlive(cOutDependenciesJsonAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cLanguagesAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineGetTtsVoices function as declared in core/moonshine-c-api.h:964
func MoonshineGetTtsVoices(Languages string, Options []MoonshineOptionT, OptionsCount uint64, OutVoicesJson **byte) int32 {
	cLanguages, cLanguagesAllocMap := unpackPCharString(Languages)
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutVoicesJson, cOutVoicesJsonAllocMap := (**C.char)(unsafe.Pointer(OutVoicesJson)), cgoAllocsUnknown
	__ret := C.moonshine_get_tts_voices(cLanguages, cOptions, cOptionsCount, cOutVoicesJson)
	runtime.KeepAlive(cOutVoicesJsonAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cLanguagesAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineGetSttDependencies function as declared in core/moonshine-c-api.h:1011
func MoonshineGetSttDependencies(Language string, Options []MoonshineOptionT, OptionsCount uint64, OutDependenciesJson **byte) int32 {
	cLanguage, cLanguageAllocMap := unpackPCharString(Language)
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutDependenciesJson, cOutDependenciesJsonAllocMap := (**C.char)(unsafe.Pointer(OutDependenciesJson)), cgoAllocsUnknown
	__ret := C.moonshine_get_stt_dependencies(cLanguage, cOptions, cOptionsCount, cOutDependenciesJson)
	runtime.KeepAlive(cOutDependenciesJsonAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cLanguageAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineGetEmbeddingDependencies function as declared in core/moonshine-c-api.h:1034
func MoonshineGetEmbeddingDependencies(ModelName string, Options []MoonshineOptionT, OptionsCount uint64, OutDependenciesJson **byte) int32 {
	cModelName, cModelNameAllocMap := unpackPCharString(ModelName)
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutDependenciesJson, cOutDependenciesJsonAllocMap := (**C.char)(unsafe.Pointer(OutDependenciesJson)), cgoAllocsUnknown
	__ret := C.moonshine_get_embedding_dependencies(cModelName, cOptions, cOptionsCount, cOutDependenciesJson)
	runtime.KeepAlive(cOutDependenciesJsonAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cModelNameAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineGetDiarizationDependencies function as declared in core/moonshine-c-api.h:1056
func MoonshineGetDiarizationDependencies(OutDependenciesJson **byte) int32 {
	cOutDependenciesJson, cOutDependenciesJsonAllocMap := (**C.char)(unsafe.Pointer(OutDependenciesJson)), cgoAllocsUnknown
	__ret := C.moonshine_get_diarization_dependencies(cOutDependenciesJson)
	runtime.KeepAlive(cOutDependenciesJsonAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineGetSttCatalog function as declared in core/moonshine-c-api.h:1065
func MoonshineGetSttCatalog(OutCatalogJson **byte) int32 {
	cOutCatalogJson, cOutCatalogJsonAllocMap := (**C.char)(unsafe.Pointer(OutCatalogJson)), cgoAllocsUnknown
	__ret := C.moonshine_get_stt_catalog(cOutCatalogJson)
	runtime.KeepAlive(cOutCatalogJsonAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineGetEmbeddingCatalog function as declared in core/moonshine-c-api.h:1075
func MoonshineGetEmbeddingCatalog(OutCatalogJson **byte) int32 {
	cOutCatalogJson, cOutCatalogJsonAllocMap := (**C.char)(unsafe.Pointer(OutCatalogJson)), cgoAllocsUnknown
	__ret := C.moonshine_get_embedding_catalog(cOutCatalogJson)
	runtime.KeepAlive(cOutCatalogJsonAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineTextToSpeech function as declared in core/moonshine-c-api.h:1087
func MoonshineTextToSpeech(TtsSynthesizerHandle int32, Text string, Options []MoonshineOptionT, OptionsCount uint64, OutAudioData [][]float32, OutAudioDataSize []uint64, OutSampleRate []int32) int32 {
	cTtsSynthesizerHandle, cTtsSynthesizerHandleAllocMap := (C.int32_t)(TtsSynthesizerHandle), cgoAllocsUnknown
	cText, cTextAllocMap := unpackPCharString(Text)
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutAudioData, cOutAudioDataAllocMap := unpackArgSSFloat32(OutAudioData)
	cOutAudioDataSize, cOutAudioDataSizeAllocMap := (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&OutAudioDataSize)).Data)), cgoAllocsUnknown
	cOutSampleRate, cOutSampleRateAllocMap := (*C.int32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&OutSampleRate)).Data)), cgoAllocsUnknown
	__ret := C.moonshine_text_to_speech(cTtsSynthesizerHandle, cText, cOptions, cOptionsCount, cOutAudioData, cOutAudioDataSize, cOutSampleRate)
	runtime.KeepAlive(cOutSampleRateAllocMap)
	runtime.KeepAlive(cOutAudioDataSizeAllocMap)
	packSSFloat32(OutAudioData, cOutAudioData)
	runtime.KeepAlive(cOutAudioDataAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cTextAllocMap)
	runtime.KeepAlive(cTtsSynthesizerHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshinePhonemesToSpeech function as declared in core/moonshine-c-api.h:1111
func MoonshinePhonemesToSpeech(TtsSynthesizerHandle int32, Phonemes string, Options []MoonshineOptionT, OptionsCount uint64, OutAudioData [][]float32, OutAudioDataSize []uint64, OutSampleRate []int32) int32 {
	cTtsSynthesizerHandle, cTtsSynthesizerHandleAllocMap := (C.int32_t)(TtsSynthesizerHandle), cgoAllocsUnknown
	cPhonemes, cPhonemesAllocMap := unpackPCharString(Phonemes)
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutAudioData, cOutAudioDataAllocMap := unpackArgSSFloat32(OutAudioData)
	cOutAudioDataSize, cOutAudioDataSizeAllocMap := (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&OutAudioDataSize)).Data)), cgoAllocsUnknown
	cOutSampleRate, cOutSampleRateAllocMap := (*C.int32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&OutSampleRate)).Data)), cgoAllocsUnknown
	__ret := C.moonshine_phonemes_to_speech(cTtsSynthesizerHandle, cPhonemes, cOptions, cOptionsCount, cOutAudioData, cOutAudioDataSize, cOutSampleRate)
	runtime.KeepAlive(cOutSampleRateAllocMap)
	runtime.KeepAlive(cOutAudioDataSizeAllocMap)
	packSSFloat32(OutAudioData, cOutAudioData)
	runtime.KeepAlive(cOutAudioDataAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cPhonemesAllocMap)
	runtime.KeepAlive(cTtsSynthesizerHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineCreateGraphemeToPhonemizerFromFiles function as declared in core/moonshine-c-api.h:1140
func MoonshineCreateGraphemeToPhonemizerFromFiles(Language string, Filenames []string, FilenamesCount uint64, Options []MoonshineOptionT, OptionsCount uint64, MoonshineVersion int32) int32 {
	cLanguage, cLanguageAllocMap := unpackPCharString(Language)
	cFilenames, cFilenamesAllocMap := unpackArgSString(Filenames)
	cFilenamesCount, cFilenamesCountAllocMap := (C.uint64_t)(FilenamesCount), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cMoonshineVersion, cMoonshineVersionAllocMap := (C.int32_t)(MoonshineVersion), cgoAllocsUnknown
	__ret := C.moonshine_create_grapheme_to_phonemizer_from_files(cLanguage, cFilenames, cFilenamesCount, cOptions, cOptionsCount, cMoonshineVersion)
	runtime.KeepAlive(cMoonshineVersionAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cFilenamesCountAllocMap)
	packSString(Filenames, cFilenames)
	runtime.KeepAlive(cFilenamesAllocMap)
	runtime.KeepAlive(cLanguageAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineCreateGraphemeToPhonemizerFromMemory function as declared in core/moonshine-c-api.h:1169
func MoonshineCreateGraphemeToPhonemizerFromMemory(Language string, Filenames []string, FilenamesCount uint64, Memory [][]byte, MemorySizes []uint64, Options []MoonshineOptionT, OptionsCount uint64, MoonshineVersion int32) int32 {
	cLanguage, cLanguageAllocMap := unpackPCharString(Language)
	cFilenames, cFilenamesAllocMap := unpackArgSString(Filenames)
	cFilenamesCount, cFilenamesCountAllocMap := (C.uint64_t)(FilenamesCount), cgoAllocsUnknown
	cMemory, cMemoryAllocMap := unpackArgSSByte(Memory)
	cMemorySizes, cMemorySizesAllocMap := (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&MemorySizes)).Data)), cgoAllocsUnknown
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cMoonshineVersion, cMoonshineVersionAllocMap := (C.int32_t)(MoonshineVersion), cgoAllocsUnknown
	__ret := C.moonshine_create_grapheme_to_phonemizer_from_memory(cLanguage, cFilenames, cFilenamesCount, cMemory, cMemorySizes, cOptions, cOptionsCount, cMoonshineVersion)
	runtime.KeepAlive(cMoonshineVersionAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cMemorySizesAllocMap)
	packSSByte(Memory, cMemory)
	runtime.KeepAlive(cMemoryAllocMap)
	runtime.KeepAlive(cFilenamesCountAllocMap)
	packSString(Filenames, cFilenames)
	runtime.KeepAlive(cFilenamesAllocMap)
	runtime.KeepAlive(cLanguageAllocMap)
	__v := (int32)(__ret)
	return __v
}

// MoonshineFreeGraphemeToPhonemizer function as declared in core/moonshine-c-api.h:1178
func MoonshineFreeGraphemeToPhonemizer(GraphemeToPhonemizerHandle int32) {
	cGraphemeToPhonemizerHandle, cGraphemeToPhonemizerHandleAllocMap := (C.int32_t)(GraphemeToPhonemizerHandle), cgoAllocsUnknown
	C.moonshine_free_grapheme_to_phonemizer(cGraphemeToPhonemizerHandle)
	runtime.KeepAlive(cGraphemeToPhonemizerHandleAllocMap)
}

// MoonshineTextToPhonemes function as declared in core/moonshine-c-api.h:1184
func MoonshineTextToPhonemes(GraphemeToPhonemizerHandle int32, Text string, Options []MoonshineOptionT, OptionsCount uint64, OutPhonemes []string, OutPhonemesCount []uint64) int32 {
	cGraphemeToPhonemizerHandle, cGraphemeToPhonemizerHandleAllocMap := (C.int32_t)(GraphemeToPhonemizerHandle), cgoAllocsUnknown
	cText, cTextAllocMap := unpackPCharString(Text)
	cOptions, cOptionsAllocMap := unpackArgSMoonshineOptionT(Options)
	cOptionsCount, cOptionsCountAllocMap := (C.uint64_t)(OptionsCount), cgoAllocsUnknown
	cOutPhonemes, cOutPhonemesAllocMap := unpackArgSString(OutPhonemes)
	cOutPhonemesCount, cOutPhonemesCountAllocMap := (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&OutPhonemesCount)).Data)), cgoAllocsUnknown
	__ret := C.moonshine_text_to_phonemes(cGraphemeToPhonemizerHandle, cText, cOptions, cOptionsCount, cOutPhonemes, cOutPhonemesCount)
	runtime.KeepAlive(cOutPhonemesCountAllocMap)
	packSString(OutPhonemes, cOutPhonemes)
	runtime.KeepAlive(cOutPhonemesAllocMap)
	runtime.KeepAlive(cOptionsCountAllocMap)
	packSMoonshineOptionT(Options, cOptions)
	runtime.KeepAlive(cOptionsAllocMap)
	runtime.KeepAlive(cTextAllocMap)
	runtime.KeepAlive(cGraphemeToPhonemizerHandleAllocMap)
	__v := (int32)(__ret)
	return __v
}
