// Copyright 2025 Moonshine AI
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../core
#cgo LDFLAGS: -L${SRCDIR}/../../../core/build -lmoonshine
#include "moonshine-c-api.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// MoonshineOptionT as declared in core/moonshine-c-api.h:146
type MoonshineOptionT struct {
	Name           []byte
	Value          []byte
	ref49bfe3c9    *C.struct_moonshine_option_t
	allocs49bfe3c9 interface{}
}

// MoonshineSpeechClipT as declared in core/moonshine-c-api.h:766
type MoonshineSpeechClipT struct {
	AudioData      []float32
	AudioLength    uint64
	StartTime      float32
	SpeechDuration float32
	IsComplete     int32
	Transcript     []byte
	ref48734c3f    *C.struct_moonshine_speech_clip_t
	allocs48734c3f interface{}
}

// SpeakerSpanT as declared in core/moonshine-c-api.h:221
type SpeakerSpanT struct {
	StartTime      float32
	Duration       float32
	SpeakerId      uint64
	SpeakerIndex   uint32
	StartChar      uint64
	EndChar        uint64
	refc74b8359    *C.struct_speaker_span_t
	allocsc74b8359 interface{}
}

// TranscriptLineT as declared in core/moonshine-c-api.h:240
type TranscriptLineT struct {
	Text                       []byte
	AudioData                  []float32
	AudioDataCount             uint64
	StartTime                  float32
	Duration                   float32
	Id                         uint64
	IsComplete                 int8
	IsUpdated                  int8
	IsNew                      int8
	HasTextChanged             int8
	HaveSpeakersChanged        int8
	SpeakerSpans               []SpeakerSpanT
	SpeakerSpanCount           uint64
	LastTranscriptionLatencyMs uint32
	Words                      []TranscriptWordT
	WordCount                  uint64
	ref4f437f7c                *C.struct_transcript_line_t
	allocs4f437f7c             interface{}
}

// TranscriptT as declared in core/moonshine-c-api.h:285
type TranscriptT struct {
	Lines          []TranscriptLineT
	LineCount      uint64
	reff65a4ca6    *C.struct_transcript_t
	allocsf65a4ca6 interface{}
}

// TranscriptWordT as declared in core/moonshine-c-api.h:203
type TranscriptWordT struct {
	Text           []byte
	Start          float32
	End            float32
	Confidence     float32
	refb21ffa94    *C.struct_transcript_word_t
	allocsb21ffa94 interface{}
}
