// Code generated by genraw; DO NOT EDIT.
// raw contains raw generated bindings to the moonshine-c-api

package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../core
#include "moonshine-c-api.h"
*/
import "C"

const (
	MoonshineEmbeddingModelArchGemma300M = C.MOONSHINE_EMBEDDING_MODEL_ARCH_GEMMA_300M
	MoonshineErrorInvalidArgument        = C.MOONSHINE_ERROR_INVALID_ARGUMENT
	MoonshineErrorInvalidHandle          = C.MOONSHINE_ERROR_INVALID_HANDLE
	MoonshineErrorNone                   = C.MOONSHINE_ERROR_NONE
	MoonshineErrorUnknown                = C.MOONSHINE_ERROR_UNKNOWN
	MoonshineFlagForceUpdate             = C.MOONSHINE_FLAG_FORCE_UPDATE
	MoonshineFlagSpellingMode            = C.MOONSHINE_FLAG_SPELLING_MODE
	MoonshineFromMemoryRemovedVersion    = C.MOONSHINE_FROM_MEMORY_REMOVED_VERSION
	MoonshineHeaderVersion               = C.MOONSHINE_HEADER_VERSION
	MoonshineModelArchBase               = C.MOONSHINE_MODEL_ARCH_BASE
	MoonshineModelArchBaseStreaming      = C.MOONSHINE_MODEL_ARCH_BASE_STREAMING
	MoonshineModelArchMediumStreaming    = C.MOONSHINE_MODEL_ARCH_MEDIUM_STREAMING
	MoonshineModelArchSmallStreaming     = C.MOONSHINE_MODEL_ARCH_SMALL_STREAMING
	MoonshineModelArchTiny               = C.MOONSHINE_MODEL_ARCH_TINY
	MoonshineModelArchTinyStreaming      = C.MOONSHINE_MODEL_ARCH_TINY_STREAMING
)
